const express = require('express');
const router  = express.Router();
const db      = require('../db');
const config  = require('../config');
const siteSettings = require('../site-settings');
const { sendPickupReminder } = require('../mailer');

// All cron endpoints share an Authorization: Bearer <secret> guard.
// Secret is in site_settings.cron_secret (auto-generated by migration 011).
async function requireCronSecret(req, res, next) {
  const settings = await siteSettings.load();
  const expected = settings.site.cronSecret || process.env.CRON_SECRET || '';
  if (!expected) return res.status(503).json({ error: 'Cron secret not configured' });
  const got = (req.get('authorization') || '').replace(/^Bearer\s+/i, '').trim();
  if (got !== expected) return res.status(401).json({ error: 'Unauthorized' });
  next();
}

// Pickup reminders. Send to every customer with an open order whose pickup event
// is within the configured lead time. Idempotent via orders.pickup_reminder_sent_at.
router.post('/pickup-reminders', requireCronSecret, async (req, res) => {
  const settings = await siteSettings.load();
  const hours = settings.site.pickupReminderHours || 24;

  const candidates = await db.query(`
    SELECT o.id AS order_id, o.customer_email, o.customer_name,
           pe.id AS event_id, pe.name AS event_name, pe.event_date, pe.event_time, pe.location
    FROM orders o
    JOIN pickup_events pe ON o.pickup_event_id = pe.id
    WHERE o.pickup_reminder_sent_at IS NULL
      AND o.customer_email <> ''
      AND o.status IN ('paid','processing','ready')
      AND pe.event_date <= (NOW() + ($1 || ' hours')::interval)::date
      AND pe.event_date >= NOW()::date
  `, [String(hours)]);

  let sent = 0, failed = 0, skipped = 0;
  for (const c of candidates.rows) {
    const result = await sendPickupReminder({
      to: c.customer_email,
      customerName: c.customer_name,
      orderId: c.order_id,
      brandName: settings.brand.name,
      baseUrl: config.baseUrl,
      eventName: c.event_name,
      eventDate: c.event_date,
      eventTime: c.event_time,
      eventLocation: c.location,
    });
    if (result.status === 'sent') sent++;
    else if (result.status === 'skipped') skipped++;
    else failed++;

    // Mark sent regardless of outcome so we don't pile up retries on a misconfigured SMTP
    await db.query('UPDATE orders SET pickup_reminder_sent_at = NOW() WHERE id = $1', [c.order_id]);
  }

  res.json({
    candidates: candidates.rows.length,
    sent, failed, skipped,
    pickup_reminder_hours: hours,
  });
});

// Auto-cancel pending orders older than 24h. Run hourly.
router.post('/cancel-stale-pending', requireCronSecret, async (req, res) => {
  const result = await db.query(`
    WITH stale AS (
      SELECT id, status FROM orders
      WHERE status = 'pending' AND created_at < NOW() - INTERVAL '24 hours'
    ),
    upd AS (
      UPDATE orders SET status = 'failed' WHERE id IN (SELECT id FROM stale) RETURNING id
    )
    INSERT INTO order_status_log (order_id, from_status, to_status, note)
    SELECT id, 'pending', 'failed', 'Auto-cancelled (no payment within 24 hours)' FROM upd
    RETURNING order_id
  `);
  res.json({ cancelled: result.rowCount });
});

module.exports = router;
